{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
data:
  api-key: {{ .Values.secrets.data.apiKey | b64enc | quote }}
{{- end -}}
