{{- if .Values.app.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels:
    app: app
    version: v2
spec:
  replicas: {{ .Values.app.canary.replicaCount }}
  selector:
    matchLabels:
      app: app
      version: v2
  template:
    metadata:
      labels:
        app: app
        version: v2
    spec:
      containers:
      - name: app
        image: "{{ .Values.app.canary.image.repository }}:{{ .Values.app.canary.image.tag }}"
        imagePullPolicy: {{ .Values.app.canary.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.service.port }}
        env:
        - name: MODEL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: model_host
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: api-key
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
{{- end }}
