apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app
    version: v1
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    metadata:
      labels:
        app: app
        version: v1
        sidecar.istio.io/inject: "{{ .Values.istio.enabled | toString }}"
    spec:
      containers:
      - name: app
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.service.port }}
        env:
        - name: MODEL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: model_host
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: api-key
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
