apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels: { release: myrelease }
spec:
  selector:
    matchLabels: { app: app }
  endpoints:
    - interval: 15s