apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels: { release: {{ .Release.Name }} }
spec:
  selector:
    matchLabels:
      app: app
  podTargetLabels:
  - version
  endpoints:
    - interval: 15s
      port: http
      path: /metrics
