{{- if .Values.istio.useGateway }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-vs
spec:
  gateways:
  - app-gateway
  hosts:
  {{- if .Values.istio.gateway.hosts }}
  {{- range .Values.istio.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  {{- else }}
  {{- range .Values.app.ingress.hosts }}
  - {{ .host | quote }}
  {{- end }}
  {{- end }}
  http:
  {{- if .Values.istio.canary.enabled }}
  - match:
    - authority:
        exact: istio.team14.local
    route:
      - destination:
          host: app
          port:
            number: {{ .Values.app.service.port }}
          subset: v1
        weight: {{ .Values.istio.canary.v1Weight }}
      - destination:
          host: app
          port:
            number: {{ .Values.app.service.port }}
          subset: v2
        weight: {{ .Values.istio.canary.v2Weight }}
  - match:
    - authority:
        exact: canary.team14.local
    route:
      - destination:
          host: app
          port:
            number: {{ .Values.app.service.port }}
          subset: v2
  {{- else }}
  - match:
    - authority:
        exact: istio.team14.local
    route:
      - destination:
          host: app
          port:
            number: {{ .Values.app.service.port }}
          subset: v1
  {{- end }}
{{- end }}

