{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-vs
spec:
  gateways:
  - app-gateway
  hosts:
  {{- range .Values.app.ingress.hosts }}
  - {{ .host | quote }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: app
        port:
          number: {{ .Values.app.service.port }}
    #     subset: v1
    #   weight: {{ .Values.istio.canary.v1Weight }}
    # - destination:
    #     host: app
    #     subset: v2
    #   weight: {{ .Values.istio.canary.v2Weight }}
{{- end }}