apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  labels:
    app: model-service
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
        sidecar.istio.io/inject: "{{ .Values.istio.enabled | toString }}"
    spec:
      containers:
      - name: model-service
        image: "{{ .Values.modelService.image.repository }}:{{ .Values.modelService.image.tag }}"
        imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
        env:
        - name: MODEL_URL
          value: {{ .Values.modelService.env.modelUrl | quote }}
        - name: APP_PORT
          value: {{ .Values.modelService.service.port | quote }}
        resources:
          {{- toYaml .Values.modelService.resources | nindent 10 }}
