{{- if .Values.modelService.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-v2
  labels:
    app: model-service
    version: v2
spec:
  replicas: {{ .Values.modelService.canary.replicaCount }}
  selector:
    matchLabels:
      app: model-service
      version: v2
  template:
    metadata:
      labels:
        app: model-service
        version: v2
    spec:
      containers:
      - name: model-service
        image: "{{ .Values.modelService.canary.image.repository }}:{{ .Values.modelService.canary.image.tag }}"
        imagePullPolicy: {{ .Values.modelService.canary.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
        env:
        - name: MODEL_URL
          value: {{ .Values.modelService.env.modelUrl | quote }}
        - name: APP_PORT
          value: {{ .Values.modelService.service.port | quote }}
        resources:
          {{- toYaml .Values.modelService.resources | nindent 10 }}
{{- end }}
