apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model-service
spec:
  type: {{ .Values.modelService.service.type }}
  selector:
    app: model-service
  ports:
    - protocol: TCP
      port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.service.port }}
