---
- hosts: "node-*"
  become: true

  tasks:
    - name: Check if node already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Read join command
      slurp:
        src: /mnt/shared/kubeadm_join.sh
      register: join_cmd_file
      when: not kubelet_conf.stat.exists

    - name: Join node to Kubernetes cluster
      command: "{{ join_cmd_file.content | b64decode }}"
      when: 
        - not kubelet_conf.stat.exists

    - name: Ensure kubelet is enabled and started
      systemd:
        name: kubelet
        enabled: true
        state: started
