- hosts: node-*
  become: true
  tasks:  
    - name: Check if node is already joined to cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Generate Join Command
      command: kubeadm token create --print-join-command
      delegate_to: ctrl
      run_once: true
      register: join_command
      when: not kubelet_conf.stat.exists
      
    - name: Run Join Command
      ansible.builtin.shell: 
        cmd: "{{ join_command.stdout }}"
      when: not kubelet_conf.stat.exists
