- hosts: node-*
  become: true
  tasks:  
    - name: Generate Join Command
      command: kubeadm token create --print-join-command
      delegate_to: ctrl
      run_once: true
      register: join_command
      
    - name: Run Join Command
      ansible.builtin.shell: 
        cmd: "{{ join_command.stdout }}"
