{{- $hosts := .Values.istio.gateway.hosts }}
{{- $host := index $hosts 0 }}
{{- if .Values.app.canary.enabled }}
{{- $host = index $hosts 1 }}
{{- end }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-gateway
  namespace: {{ .Values.istio.ratelimit.namespace }}
spec:
  workloadSelector:
    labels:
      istio: {{ .Values.istio.gateway.selector.istio }}
  configPatches:
    # PATCH 1: The Filter (The "Hardware" connection) - This part is likely fine
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: {{ .Values.istio.ratelimit.domain }}
            failure_mode_deny: {{ .Values.istio.ratelimit.failureModeDeny }} 
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|{{ .Values.istio.ratelimit.service.port }}||{{ .Values.istio.ratelimit.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
              transport_api_version: V3

    # PATCH 2: The Action (The Instruction) - Targeting the specific host
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "{{ $host }}:{{ .Values.istio.ratelimit.vhost.port }}"
      patch:
        operation: MERGE
        value:
          rate_limits:
            - actions:
                - request_headers:
                    header_name: "{{ .Values.istio.ratelimit.descriptor.path.headerName }}"
                    descriptor_key: "{{ .Values.istio.ratelimit.descriptor.path.key }}"
                    
                - request_headers:
                    header_name: "{{ .Values.istio.ratelimit.descriptor.user.headerName }}"
                    descriptor_key: "{{ .Values.istio.ratelimit.descriptor.user.key }}"

                    
